'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { CalendarDays, ChevronDown, Footprints, LockKeyhole, Trophy, Mountain, Accessibility, Waves } from 'lucide-react'
import { Header } from '@/components/foorun-challenges'
import FooRunFooter from '@/components/Footer'

const orange = '#fc5200'
const hero = 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=1800&q=88'
const reward = 'https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=900&q=88'

const athletes = [
  ['Tatiana Hill', 'Rising Fawn, GA 30738, USA, GA', '167h 10m', '6,687%'],
  ['Govin Shrestha', 'Juba, Central Equatoria, South Sudan', '153h 10m', '6,127%'],
  ['Klaus-Peter Schumacher', 'Illingen, Saarland, Germany', '152h 45m', '6,111%'],
  ['Mawi Zzz..', 'Bandar Lampung, Indonesia', '133h 27m', '5,338%'],
  ['Anton Svensson', 'Götene', '126h 0m', '5,041%'],
  ['Joseph Castelo', 'New Bedford, Massachusetts', '125h 43m', '5,029%'],
]

function CountUp() { const [count, setCount] = useState(0); useEffect(() => { let n = 0; const timer = setInterval(() => { n += 14000; if (n >= 421650) { setCount(421650); clearInterval(timer) } else setCount(n) }, 30); return () => clearInterval(timer) }, []); return <span>{count.toLocaleString()}</span> }

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="border-t border-[#e5e5e8] py-8"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-medium text-[#18181b]">{title}</h2><button aria-label={`Toggle ${title}`} className="p-2"><ChevronDown size={19} /></button></div>{children}</section> }

function DetailHero() { return <><div className="relative h-[330px] overflow-hidden sm:h-[440px]"><img src={hero} alt="Two runners training together on a city street" className="h-full w-full object-cover object-center" /><div className="absolute inset-0 bg-gradient-to-t from-black/25 to-transparent" /><div className="absolute bottom-[-38px] left-1/2 flex h-28 w-28 -translate-x-1/2 rotate-45 items-center justify-center bg-gradient-to-br from-[#9da5b5] to-[#252b3a] shadow-xl"><div className="-rotate-45 text-center text-white"><div className="text-[9px] font-bold tracking-widest">BANDIT</div><div className="mt-1 text-4xl font-black">R</div></div></div></div><section className="mx-auto max-w-[1220px] px-5 pb-10 pt-20 text-center"><h1 className="text-4xl font-black tracking-[-.04em] text-black sm:text-5xl">The Forge with Bandit Running</h1><p className="mt-3 text-xl text-[#17171a]">The hard days shape what comes next.</p></section></> }

function Metadata() { return <section className="mx-auto grid max-w-[1220px] gap-10 border-b border-[#e5e5e8] px-5 pb-16 lg:grid-cols-[1fr_345px]"><div className="space-y-7"><div className="flex gap-5"><CalendarDays className="mt-0.5 shrink-0" size={25} /><div>Sep 14, 2026 to Sep 28, 2026 — 2 days left</div></div><div className="flex gap-5"><Footprints className="mt-0.5 shrink-0" size={25} /><div><div>Complete 150 minutes</div><a href="#details" className="text-xs text-sky-600">Qualifying Activities: Hike, Run, Trail Run, Virtual Run, Walk, Wheelchair</a></div></div><div className="flex gap-5"><Trophy className="mt-0.5 shrink-0 text-amber-500" size={25} /><div>Complete 150 minutes to unlock a unique FooRun Badge, entry to win exclusive Bandit prizes and up to 20% off</div></div></div><aside className="space-y-5"><button className="min-h-11 w-full rounded bg-[#fc5200] px-5 text-sm font-medium text-white hover:bg-[#e84d00]">Join Challenge</button><button className="min-h-11 w-full rounded border border-[#fc5200] px-5 text-sm font-medium text-[#fc5200] hover:bg-[#fff4ef]">Invite Friends</button><div className="pt-5 text-center"><div className="text-xs text-[#777780]">Participants</div><div className="text-2xl"><CountUp /></div></div></aside></section> }

function Overview() { return <Section title="Overview"><div className="max-w-[700px] space-y-4 text-sm leading-6 text-[#777780]"><p>September is the forge. For runners preparing for a fall goal, it&apos;s where training reaches its most demanding point. The work gets harder, fatigue builds, and the moment you&apos;ve been preparing for is finally coming into view.</p><p>This is the month that tests the work you&apos;ve put in and builds the strength you&apos;ll carry into race day. Long runs, hard workouts, and tired legs aren&apos;t obstacles to the process, they are the reason. Embrace the adversity, stay consistent, and keep going.</p><p>The moment will show what you can do. The Forge is where you build it.</p><p>By completing 150 minutes, you&apos;ll earn a limited-edition FooRun badge and an exclusive 20% discount on your next Bandit order.</p></div></Section> }

function Leaderboard() { return <Section title="Leaderboard"><div className="max-w-[710px]"><p className="mb-4 text-sm">Current Place: -- / 288,571</p><div className="mb-3 flex gap-2 bg-[#f5f5f7] p-3 text-[11px] leading-4"><LockKeyhole size={14} className="shrink-0" />Any qualifying activity, whether private or not, will count towards your private progress, badges, and rewards for this challenge.</div><div className="mb-5 flex flex-wrap border-b border-[#d9d9dd] text-xs">{['Overall', "I'm Following", 'My Clubs', 'By Country', 'By Age', 'By Weight'].map((tab, i) => <button key={tab} className={`min-h-12 border-x border-t px-4 ${i === 0 ? 'border-t-2 border-t-[#fc5200] font-semibold' : 'border-transparent'}`}>{tab}</button>)}<button className="m-2 rounded border border-[#d9d9dd] px-4">Overall⌄</button></div><div className="grid grid-cols-[34px_1fr_100px_140px] border-b py-2 text-[10px] font-bold uppercase"><span>Overall</span><span>Name</span><span>Time</span><span>Progress</span></div>{athletes.map(([name, location, time, percent], index) => <div key={name} className="grid grid-cols-[34px_1fr_100px_140px] items-center border-b border-[#dedee2] py-3 text-xs"><span className="text-center text-[#777780]">{index + 1}</span><div className="flex items-center gap-3"><div className="h-8 w-8 rounded-full bg-gradient-to-br from-slate-300 to-slate-600" /><div><div className="text-sm text-[#777780]">{name}</div><div className="text-[10px] text-[#777780]">{location}</div></div></div><span className="text-[#777780]">{time}</span><div className="flex items-center gap-2"><div className="h-3 w-20 bg-emerald-400" /><span className="text-[#777780]">{percent}</span></div></div>)}</div></Section> }

function Details() { return <Section title="Details & Eligibility"><div id="details" className="max-w-[710px] space-y-5 text-sm leading-6 text-[#777780]"><div>Rewards</div><p>By completing 150 minutes, you&apos;ll earn a limited-edition FooRun badge and an exclusive 20% discount on your next Bandit order.</p><img src={reward} alt="Runners training outdoors" className="h-48 w-full max-w-[375px] object-cover" /><div>Additional Info</div><p>This Challenge starts and ends based on each participant&apos;s local time zone.</p><p>GPS, virtual, and manual activities will count towards the Challenge goal. There is no minimum time per activity; Challenge progress is determined by an activity&apos;s moving time.</p><p>Activities visible to &quot;Everyone,&quot; &quot;Only You&quot; or &quot;Followers&quot; are eligible for this Challenge.</p><div className="pt-3">Qualifying Activities</div><div className="grid max-w-[430px] grid-cols-2 gap-4 text-[#242429]">{[['Hike', Mountain], ['Run', Footprints], ['Trail Run', Footprints], ['Virtual Run', Footprints], ['Walk', Footprints], ['Wheelchair', Accessibility]].map(([label, Icon]) => <div key={String(label)} className="flex items-center gap-3"><Icon size={17} />{String(label)}</div>)}</div></div></Section> }

export default function FooRunChallengeDetail() { return <div dir="ltr" className="min-h-screen bg-white text-[#17171a]"><Header /><main><DetailHero /><Metadata /><div className="mx-auto grid max-w-[1220px] gap-14 px-5 py-10 lg:grid-cols-[minmax(0,710px)_1fr]"><div><Overview /><Leaderboard /><Details /></div><aside className="hidden pt-10 lg:block"><div className="sticky top-24 text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded bg-black text-sm font-bold text-white">R BANDIT</div><div className="mt-3 text-[10px] uppercase tracking-wider">Organizing Club</div><h3 className="mt-3 text-xl">Bandit Running</h3><div className="mt-2 text-sm">♧ 99,770 athletes</div><button className="mt-5 min-h-11 w-full rounded border border-[#fc5200] text-sm text-[#fc5200]">Join Club</button></div></aside></div></main><FooRunFooter /></div> }
