'use client'

import Link from 'next/link'
import { useState } from 'react'
import { Bell, Bike, CalendarDays, ChevronDown, ChevronRight, Footprints, Gauge, Medal, Mountain, Trophy, Waves } from 'lucide-react'
import FooRunFooter from '@/components/Footer'

const orange = '#FC5200'

type Challenge = { title: string; image: string; badge: string; detail: string; date: string; icon: typeof Footprints; href?: string }

const filters = [
  { label: 'Run', icon: Footprints }, { label: 'Ride', icon: Bike }, { label: 'Swim', icon: Waves },
  { label: 'Walk', icon: Footprints }, { label: 'Hike', icon: Mountain }, { label: 'Workout', icon: Gauge },
  { label: 'Distance', icon: null }, { label: 'Elevation Gain', icon: null }, { label: 'Moving Time', icon: null },
]

const challenges: Challenge[] = [
  { title: 'چالش ۴۰۰ دقیقه‌ای Runna', image: 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=900&q=85', badge: '400', detail: 'Complete 400 mins of activity in October', date: 'Oct 1, 2026 to Oct 31, 2026', icon: Footprints },
  { title: '۱۰ روز پیاپی فعالیت ورزشی', image: 'https://images.unsplash.com/photo-1530137073524-4e7d0f4c0d92?auto=format&fit=crop&w=900&q=85', badge: '10x', detail: 'Log 10 days of activity in September', date: 'Sep 1, 2026 to Sep 30, 2026', icon: Trophy },
  { title: 'جامعه دوندگان: رویش دوباره', image: 'https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&w=900&q=85', badge: '4 WEEKS', detail: 'Log an activity each week, for 4 weeks', date: 'Sep 14, 2026 to Oct 20, 2026', icon: Waves },
  { title: 'The Forge with Bandit Running', image: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=900&q=85', badge: '150', detail: 'Complete 150 minutes', date: 'Sep 14, 2026 to Sep 28, 2026', icon: Footprints, href: '/challenges/the-forge' },
  { title: 'September 5K x Brooks Challenge', image: 'https://images.unsplash.com/photo-1502904550040-7534597429ae?auto=format&fit=crop&w=900&q=85', badge: '5K', detail: 'Complete a 5K run', date: 'Sep 1, 2026 to Sep 30, 2026', icon: Footprints },
  { title: 'Virtual TCS New York City Marathon', image: 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=900&q=85', badge: '26.2', detail: 'Complete 26.2 miles', date: 'Oct 1, 2026 to Oct 31, 2026', icon: Medal },
  { title: 'September 400-minute Challenge', image: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=900&q=85', badge: '400', detail: 'Complete 400 minutes of activity', date: 'Sep 1, 2026 to Sep 30, 2026', icon: Trophy },
  { title: 'October Ten Days Active Challenge', image: 'https://images.unsplash.com/photo-1571008887538-b36bb32f4571?auto=format&fit=crop&w=900&q=85', badge: '10x', detail: 'Do 10 days of activity', date: 'Oct 1, 2026 to Oct 31, 2026', icon: Footprints },
]

function Logo() { return <Link href="/" aria-label="FooRun home" className="flex items-center gap-2 text-[26px] font-black tracking-[-0.08em]"><span className="text-[#fc5200]" aria-hidden="true">✦</span><span><b className="text-[#fc5200]">Foo</b>Run</span></Link> }

function Header() { return <header className="sticky top-0 z-30 border-b border-[#e6e6e8] bg-white"><div className="mx-auto flex h-[72px] max-w-[1220px] items-center gap-8 px-5"><Logo /><nav className="hidden h-full items-center gap-8 text-sm text-[#55555d] md:flex"><Link href="/dashboard">Dashboard <ChevronDown size={15} className="ml-1 inline" /></Link><a href="#training">Training <ChevronDown size={15} className="ml-1 inline" /></a><Link href="/maps">Maps</Link><Link href="/challenges" className="flex h-full items-center border-b-2 border-[#fc5200] font-semibold text-[#17171a]">Challenges</Link></nav><div className="ml-auto flex items-center gap-3"><button className="hidden rounded border border-[#d9d9dd] px-5 py-2 text-sm font-semibold md:block">Give a Gift</button><button className="rounded bg-[#fc5200] px-5 py-2.5 text-sm font-bold text-white hover:bg-[#e84c00]">Start Trial</button><button aria-label="Notifications" className="hidden p-2 text-[#666] sm:block"><Bell size={21} /></button><button aria-label="Account menu" className="flex items-center gap-2"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#f57413] text-white">Z</span><ChevronDown size={15} /></button><button aria-label="Create" className="ml-2 text-2xl font-light text-[#fc5200]">⊕</button></div></div></header> }

function Hero() { return <section className="mx-auto mt-7 max-w-[1220px] overflow-hidden rounded-md bg-[#fc5200] shadow-sm"><div className="relative grid min-h-[330px] items-center overflow-hidden lg:grid-cols-[280px_1fr]"><div className="absolute inset-0 opacity-35" style={{ backgroundImage: 'radial-gradient(circle at 73% 35%, transparent 0 15%, rgba(255,255,255,.9) 15.5% 16%, transparent 16.5% 22%, rgba(255,255,255,.7) 22.5% 23%, transparent 23.5%), repeating-linear-gradient(112deg, transparent 0 42px, rgba(255,199,120,.32) 44px 46px)' }} /><div className="relative z-10 self-stretch bg-white/95 p-7 lg:flex lg:flex-col lg:justify-center"><div className="mb-6 flex h-14 w-14 items-center justify-center rounded-full border-2 border-[#fc5200] bg-white text-center text-[11px] font-black leading-3 text-[#fc5200]">180<br />MIN</div><h1 className="text-2xl font-black leading-tight text-[#202024]">چالش ۱۸۰ دقیقه عرق‌ریزی آبان</h1><p className="mt-3 text-sm leading-6 text-[#55555d]">با یک فعالیت ۱۸۰ دقیقه‌ای، نشان ویژه‌ی FooRun را به دست بیاورید.</p><div className="mt-5 flex items-center gap-2 text-sm text-[#333338]"><CalendarDays size={17} /> Nov 1, 2026 to Nov 30, 2026</div></div><div className="relative z-10 p-8 text-white sm:p-12"><div className="max-w-[640px]"><div className="text-[68px] font-black leading-none tracking-[-.08em] text-white drop-shadow-sm sm:text-[112px]">FOORUN</div><div className="mt-2 h-10 w-[92%] rounded-[50%] border-[7px] border-white/90 rotate-[-5deg]" /><div className="mt-12 flex flex-wrap items-center justify-between gap-5"><div className="flex items-center gap-3 text-sm"><Trophy size={22} /><span>Complete 180 minutes to unlock an exclusive FooRun badge</span></div><button className="rounded bg-white px-8 py-3 text-sm font-semibold text-[#fc5200] hover:bg-orange-50">Join Challenge</button></div></div></div></div></section> }

function ChallengeCard({ challenge }: { challenge: Challenge }) { const Icon = challenge.icon; const card = <article className="group overflow-hidden rounded-md border border-[#e5e5e8] bg-white shadow-[0_1px_3px_rgba(0,0,0,.08)] transition duration-200 hover:-translate-y-1 hover:shadow-xl"><div className="relative h-[150px] overflow-hidden"><img src={challenge.image} alt="" className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /><div className="absolute left-4 top-4 flex h-12 w-12 items-center justify-center rounded-full border-2 border-white bg-[#fc5200] text-center text-xs font-black leading-3 text-white shadow">{challenge.badge}</div></div><div className="p-4"><h3 className="min-h-[48px] text-[17px] font-semibold leading-6 text-[#25252a]">{challenge.title}</h3><div className="mt-2 flex gap-2 text-xs leading-5 text-[#56565f]"><Icon size={16} className="mt-0.5 shrink-0 text-[#202024]" /><span>{challenge.detail}<br />{challenge.date}</span></div><button className="mt-5 min-h-11 w-full rounded bg-[#fc5200] px-4 text-sm font-semibold text-white transition hover:bg-[#e94b00]">Join Challenge</button></div></article>; return challenge.href ? <Link href={challenge.href}>{card}</Link> : card }

export default function FooRunChallenges() { const [active, setActive] = useState('Run'); return <div dir="ltr" className="min-h-screen bg-[#fafafa] text-[#17171a]"><Header /><main className="px-5 pb-20"><Hero /><section className="mx-auto mt-8 max-w-[1220px]"><div className="flex gap-2 overflow-x-auto pb-2" role="group" aria-label="Challenge filters">{filters.map(({ label, icon: Icon }) => <button key={label} onClick={() => setActive(label)} aria-pressed={active === label} className={`flex min-h-11 shrink-0 items-center gap-2 rounded-md border px-4 text-sm transition ${active === label ? 'border-[#fc5200] bg-[#fff4ef] text-[#fc5200]' : 'border-[#dcdce0] bg-white text-[#333338] hover:border-[#fc5200]'}`}>{Icon && <Icon size={16} />}{label}</button>)}</div><div className="mb-5 mt-7 flex items-center gap-3"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-[#fc5200] text-sm font-bold text-white">Z</span><h2 className="text-[22px] font-medium text-[#202024]">پیشنهاد شده برای شما</h2><span className="text-sm text-[#777780]">Recommended For You</span></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{challenges.map((challenge) => <ChallengeCard key={challenge.title} challenge={challenge} />)}</div></section></main><FooRunFooter /></div> }

export { Header }
