'use client'

import { useMemo, useState } from 'react'
import { Activity, Bike, CalendarDays, ChevronLeft, ChevronRight, Download, Dumbbell, Flame, HeartPulse, ListFilter, Moon, Play, Plus, Ruler, Search, Sparkles, Target, Waves } from 'lucide-react'
import { Header } from '@/components/foorun-dashboard'
import { useLanguageAndTheme } from '@/components/language-theme-context'

type TrainingSlug = 'calendar' | 'activities' | 'log' | 'plans' | 'power-curve' | 'fitness'
const orange = '#FC5200'
const copy = {
  fa: {
    calendar: ['تقویم تمرین', 'ریتم تمرینت را در یک نگاه دنبال کن.'], activities: ['فعالیت‌های من', 'تمام تمرین‌هایت، مرتب و قابل جستجو.'], log: ['لاگ تمرین', 'حجم و شدت تمرینت را هوشمندانه مدیریت کن.'], plans: ['برنامه‌های تمرینی', 'برای هدف بعدی‌ات با برنامه پیش برو.'], 'power-curve': ['منحنی توان', 'بهترین عملکردت را در هر مدت زمان ببین.'], fitness: ['آمادگی و تازگی', 'تعادل تمرین، خستگی و فرم را دنبال کن.'],
    month: 'شهریور ۱۴۰۵', recorded: 'تمرین ثبت‌شده', rest: 'استراحت', run: 'دویدن', ride: 'دوچرخه', swim: 'شنا', export: 'خروجی گرفتن', filter: 'فیلتر', create: 'شروع برنامه', week: 'هفته', fitnessLabel: 'آمادگی', fatigue: 'خستگی', form: 'فرم', volume: 'حجم هفتگی', intensity: 'شدت', easy: 'آسان', moderate: 'متوسط', hard: 'سخت', activeDays: 'روز فعال', weeks: 'هفته', sessions: 'جلسه در هفته'
  },
  en: {
    calendar: ['Training Calendar', 'See your training rhythm at a glance.'], activities: ['My Activities', 'Every workout, organized and searchable.'], log: ['Training Log', 'Manage volume and intensity with clarity.'], plans: ['Training Plans', 'Move toward your next goal with a plan.'], 'power-curve': ['Power Curve', 'See your best performance across durations.'], fitness: ['Fitness & Freshness', 'Track the balance between training, fatigue, and form.'],
    month: 'September 2026', recorded: 'Recorded workout', rest: 'Rest day', run: 'Run', ride: 'Ride', swim: 'Swim', export: 'Export', filter: 'Filter', create: 'Start plan', week: 'Week', fitnessLabel: 'Fitness', fatigue: 'Fatigue', form: 'Form', volume: 'Volume by week', intensity: 'Intensity', easy: 'Easy', moderate: 'Moderate', hard: 'Hard', activeDays: 'active days', weeks: 'weeks', sessions: 'sessions / week'
  }
} as const

type TrainingCopy = typeof copy.fa | typeof copy.en

function Card({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <section className={`rounded-2xl border border-white/10 bg-[#202126] shadow-[0_18px_50px_rgba(0,0,0,.18)] ${className}`}>{children}</section> }
function Button({ children, variant = 'ghost', onClick }: { children: React.ReactNode; variant?: 'ghost' | 'primary'; onClick?: () => void }) { return <button onClick={onClick} className={`inline-flex min-h-11 items-center justify-center gap-2 rounded-xl px-4 text-sm font-semibold transition ${variant === 'primary' ? 'bg-[#fc5200] text-white shadow-[0_0_22px_rgba(252,82,0,.25)] hover:bg-[#ff6a24]' : 'border border-white/10 bg-white/[.04] text-white/75 hover:bg-white/[.08]'}`}>{children}</button> }

function CalendarPage({ t }: { t: TrainingCopy }) {
  const [year, setYear] = useState(2026)
  const isFa = t === copy.fa
  const months = isFa ? ['ژانویه','فوریه','مارس','آوریل','مه','ژوئن','ژوئیه','اوت','سپتامبر','اکتبر','نوامبر','دسامبر'] : ['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC']
  const stats = isFa ? [['ساعت', '0'], ['کیلومتر', '0'], ['رکورد شخصی', '0'], ['فعالیت‌ها', '0']] : [['Hours', '0'], ['Kilometers', '0'], ['Personal Records', '0'], ['Activities', '0']]
  return <div className="space-y-10">
    <div className="flex flex-col gap-8 border-b border-slate-200 pb-8 dark:border-white/10 lg:flex-row lg:items-end lg:justify-between">
      <div><h2 className="text-3xl font-bold tracking-tight text-slate-900 dark:text-white md:text-4xl">{isFa ? 'تقویم تمرینات' : 'Training Calendar'}</h2><div className="mt-5 flex items-center gap-5 text-2xl text-slate-700 dark:text-white"><button aria-label="Previous year" onClick={() => setYear((value) => value - 1)}><ChevronLeft /></button><span>{year}</span><button aria-label="Next year" onClick={() => setYear((value) => value + 1)}><ChevronRight /></button></div></div>
      <div className="grid grid-cols-2 gap-x-8 gap-y-5 sm:grid-cols-4">{stats.map(([label, value]) => <div key={label} className="min-w-[90px] text-center"><p className="text-2xl font-medium text-slate-900 dark:text-white">{value}</p><p className="mt-1 text-xs text-slate-500 dark:text-white/45">{label}</p></div>)}</div>
    </div>
    <div className="flex items-center gap-3"><div className="h-px flex-1 bg-[#159bd7]" /><span className="text-xs font-medium text-slate-500 dark:text-white/45">52 WEEKS</span></div>
    <div className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-4">{months.map((month, index) => <article key={month} className="min-h-[190px] border border-slate-200 bg-slate-50 p-5 transition hover:border-[#fc5200]/50 dark:border-white/[.07] dark:bg-white/[.025]"><h3 className="text-right text-xl font-normal text-slate-500 dark:text-white/55">{month}</h3><div className="mt-5 grid grid-cols-7 gap-1">{Array.from({ length: 35 }, (_, day) => { const active = (day + index * 3) % 11 === 0; return <span key={day} className={`aspect-square rounded-[2px] ${active ? 'bg-[#fc5200] shadow-[0_0_7px_rgba(252,82,0,.5)]' : 'bg-slate-200 dark:bg-white/[.06]'}`} /> })}</div><p className="mt-4 text-xs text-slate-400 dark:text-white/30">{index % 3 === 0 ? (isFa ? 'تمرینی ثبت نشده' : 'No recorded activities') : (isFa ? 'تمرین ثبت‌شده' : 'Recorded workout')}</p></article>)}</div>
  </div>
}

function ActivitiesPage({ t }: { t: TrainingCopy }) { const [filter, setFilter] = useState('all'); const rows = [{ type: 'run', name: 'Morning Tempo', date: 'Sep 18, 2026', distance: '8.6 km', time: '42:18', icon: Activity }, { type: 'ride', name: 'City Loop', date: 'Sep 16, 2026', distance: '34.2 km', time: '1:21:04', icon: Bike }, { type: 'swim', name: 'Pool Intervals', date: 'Sep 14, 2026', distance: '2.4 km', time: '48:22', icon: Waves }, { type: 'run', name: 'Long Run', date: 'Sep 12, 2026', distance: '18.1 km', time: '1:36:08', icon: Activity }]; const filtered = filter === 'all' ? rows : rows.filter((row) => row.type === filter); const labels = { all: 'All', run: t.run, ride: t.ride, swim: t.swim }; return <Card className="overflow-hidden"><div className="flex flex-col gap-3 border-b border-white/10 p-5 md:flex-row md:items-center md:justify-between"><div className="flex flex-wrap gap-2">{Object.entries(labels).map(([key, label]) => <button key={key} onClick={() => setFilter(key)} className={`min-h-10 rounded-lg px-3 text-sm ${filter === key ? 'bg-[#fc5200] text-white' : 'bg-white/[.05] text-white/55 hover:bg-white/10'}`}>{label}</button>)}</div><Button><Download size={16} />{t.export}</Button></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="text-xs text-white/35"><tr>{['Activity', 'Date', 'Distance', 'Moving time'].map((heading) => <th key={heading} className="px-5 py-4 font-medium">{heading}</th>)}</tr></thead><tbody>{filtered.map((row) => { const Icon = row.icon; return <tr key={row.name} className="border-t border-white/[.07] text-white/75"><td className="px-5 py-5"><div className="flex items-center gap-3"><Icon size={18} className="text-[#fc5200]" /><span className="font-semibold text-white">{row.name}</span></div></td><td className="px-5 py-5 text-white/45">{row.date}</td><td className="px-5 py-5">{row.distance}</td><td className="px-5 py-5">{row.time}</td></tr>})}</tbody></table></div></Card> }

function LogPage({ t }: { t: TrainingCopy }) { const volume = [52, 68, 42, 86, 74, 60, 92, 78, 50, 84, 70, 94]; return <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_300px]"><Card className="p-6"><div className="flex items-center justify-between"><div><p className="text-xs text-white/40">{t.week} 38</p><h2 className="mt-1 text-xl font-semibold">{t.volume}</h2></div><Ruler className="text-[#fc5200]" /></div><div className="mt-12 flex h-64 items-end gap-2 md:gap-4">{volume.map((height, index) => <div key={index} className="flex flex-1 flex-col items-center gap-3"><div className="w-full rounded-t-lg bg-gradient-to-t from-[#fc5200] to-[#ff9b68] shadow-[0_0_18px_rgba(252,82,0,.28)]" style={{ height: `${height}%` }} /><span className="text-[10px] text-white/35">W{index + 1}</span></div>)}</div></Card><Card className="p-6"><h2 className="font-semibold">{t.intensity}</h2><div className="mt-7 space-y-5">{[[t.easy, '68%', 'bg-[#00c889]'], [t.moderate, '48%', 'bg-[#ffc857]'], [t.hard, '27%', 'bg-[#fc5200]']].map(([label, width, color]) => <div key={label}><div className="mb-2 flex justify-between text-xs text-white/55"><span>{label}</span><span>{width}</span></div><div className="h-2 rounded-full bg-white/10"><div className={`h-full rounded-full ${color}`} style={{ width }} /></div></div>)}</div></Card></div> }

function PlansPage({ t }: { t: TrainingCopy }) { const plans = [{ title: 'Marathon Builder', detail: '16 weeks · 4 sessions / week', icon: Flame, color: 'from-[#fc5200] to-[#ff9b68]' }, { title: '10K Performance', detail: '8 weeks · 3 sessions / week', icon: Target, color: 'from-[#7c5cff] to-[#b6a5ff]' }, { title: 'Cycling Base', detail: '12 weeks · 4 rides / week', icon: Bike, color: 'from-[#00a878] to-[#8ef5d1]' }]; return <div className="grid gap-5 md:grid-cols-3">{plans.map((plan) => { const Icon = plan.icon; return <Card key={plan.title} className="group overflow-hidden"><div className={`flex h-36 items-end bg-gradient-to-br ${plan.color} p-6`}><Icon size={34} className="text-white/90" /></div><div className="p-6"><h2 className="font-semibold">{plan.title}</h2><p className="mt-2 text-sm text-white/45">{plan.detail}</p><Button variant="primary">{t.create}<Plus size={16} /></Button></div></Card> })}</div> }

function LineChart({ points, color = orange }: { points: number[]; color?: string }) { const polyline = points.map((point, index) => `${(index / (points.length - 1)) * 100},${100 - point}`).join(' '); return <svg viewBox="0 0 100 100" preserveAspectRatio="none" className="h-72 w-full overflow-visible"><defs><linearGradient id="chart-fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor={color} stopOpacity=".3" /><stop offset="1" stopColor={color} stopOpacity="0" /></linearGradient></defs><path d={`M 0,100 L ${polyline} L 100,100 Z`} fill="url(#chart-fill)" /><polyline points={polyline} fill="none" stroke={color} strokeWidth="1.8" vectorEffect="non-scaling-stroke" /></svg> }
function PowerPage({ t }: { t: TrainingCopy }) { const [duration, setDuration] = useState(30); const points = [72, 80, 67, 63, 59, 54, 50, 48, 45, 42]; return <Card className="p-6 md:p-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-semibold">Power / Pace Curve</h2><p className="mt-1 text-sm text-white/45">{duration}s duration · 420 W best effort</p></div><div className="flex gap-2">{[30, 60, 300].map((value) => <button key={value} onClick={() => setDuration(value)} className={`min-h-10 rounded-lg px-3 text-xs ${duration === value ? 'bg-[#fc5200] text-white' : 'bg-white/[.05] text-white/50'}`}>{value}s</button>)}</div></div><div className="mt-10 grid grid-cols-[auto_1fr] gap-4"><div className="flex h-72 flex-col justify-between text-[10px] text-white/30"><span>600 W</span><span>450 W</span><span>300 W</span><span>150 W</span><span>0</span></div><div className="relative border-b border-l border-white/10"><div className="absolute inset-0 flex flex-col justify-between"><i className="border-t border-dashed border-white/[.06]" /><i className="border-t border-dashed border-white/[.06]" /><i className="border-t border-dashed border-white/[.06]" /><i className="border-t border-dashed border-white/[.06]" /><i className="border-t border-dashed border-white/[.06]" /></div><LineChart points={points} /></div></div></Card> }
function FitnessPage({ t }: { t: TrainingCopy }) { return <Card className="p-6 md:p-8"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-xl font-semibold">Fitness, Fatigue & Form</h2><p className="mt-1 text-sm text-white/45">Last 12 weeks</p></div><div className="flex flex-wrap gap-4 text-xs text-white/55"><span><i className="me-2 inline-block h-2 w-2 rounded-full bg-[#00c889]" />{t.fitnessLabel}</span><span><i className="me-2 inline-block h-2 w-2 rounded-full bg-[#fc5200]" />{t.fatigue}</span><span><i className="me-2 inline-block h-2 w-2 rounded-full bg-[#7c5cff]" />{t.form}</span></div></div><div className="mt-8 grid grid-cols-[auto_1fr] gap-4"><div className="flex h-72 flex-col justify-between text-[10px] text-white/30"><span>100</span><span>75</span><span>50</span><span>25</span><span>0</span></div><div className="relative h-72 border-b border-l border-white/10"><div className="absolute inset-0 flex flex-col justify-between"><i className="border-t border-dashed border-white/[.06]" /><i className="border-t border-dashed border-white/[.06]" /><i className="border-t border-dashed border-white/[.06]" /><i className="border-t border-dashed border-white/[.06]" /><i className="border-t border-dashed border-white/[.06]" /></div><div className="absolute inset-0"><LineChart points={[38,42,45,50,47,58,60,65,63,72,78,74]} color="#00c889" /><LineChart points={[20,32,27,45,52,48,60,67,55,72,66,60]} color="#fc5200" /><LineChart points={[60,52,58,54,45,48,43,42,50,46,55,62]} color="#7c5cff" /></div></div></div></Card> }

export default function FooRunTrainingSubpage({ slug }: { slug: TrainingSlug }) { const { language } = useLanguageAndTheme(); const fa = language === 'fa'; const t = copy[language]; const [title, description] = t[slug]; const content = slug === 'calendar' ? <CalendarPage t={t} /> : slug === 'activities' ? <ActivitiesPage t={t} /> : slug === 'log' ? <LogPage t={t} /> : slug === 'plans' ? <PlansPage t={t} /> : slug === 'power-curve' ? <PowerPage t={t} /> : <FitnessPage t={t} />; return <div dir={fa ? 'rtl' : 'ltr'} className="min-h-screen bg-white text-slate-900 dark:bg-[#080b10] dark:text-white"><Header /><main className="mx-auto max-w-[1180px] px-5 py-10 md:py-14"><div className="mb-8 border-b border-white/10 pb-7"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#fc5200]">FooRun Training</p><h1 className="mt-3 text-3xl font-semibold tracking-[-.03em] md:text-5xl">{slug === 'calendar' ? (fa ? 'تقویم تمرینات / Training Calendar' : 'Training Calendar') : title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/45">{description}</p></div>{content}</main></div> }
export type { TrainingSlug }
